#!/bin/bash
# ============================================
# ArabiLogia Deploy Script v7.3 (AI Release Notes)
# ============================================

set -o pipefail

# Source all modules
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/deploy-env.sh"
source "$SCRIPT_DIR/deploy-ui.sh"
source "$SCRIPT_DIR/deploy-build.sh"
source "$SCRIPT_DIR/deploy-publish.sh"

# AI Release Notes Generator using Google Gemini
# Optional: Set GOOGLE_AI in .env to enable, or pass --no-ai to disable
generate_ai_release_notes() {
    local release_notes_file="$OUTPUT_DIR/release-notes.md"
    local version="$VERSION"
    
    # Check if AI is disabled or no API key
    if [ "$USE_AI" = "no" ] || [ -z "$GOOGLE_AI" ]; then
        print_status "Skipping AI release notes (not configured)" "$YELLOW"
        return 0
    fi
    
    print_status "Generating AI release notes (using Google Gemini)..." "$CYAN"
    
    # Get git log for changes since last tag
    local last_tag
    last_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
    local changes_log
    changes_log=$(git log "$last_tag..HEAD" --oneline --pretty=format:"- %s (%h)" 2>/dev/null || echo "")
    
    if [ -z "$changes_log" ]; then
        changes_log=$(git log -10 --oneline --pretty=format:"- %s (%h)" 2>/dev/null || echo "")
    fi
    
    # Build prompt for Gemini
    local prompt="You are a release notes writer for a Flutter mobile app called ArabiLogia (an Arabic language learning app). 
Write compelling, user-friendly release notes for version $version.

Recent changes in this release:
$changes_log

Write in English. Be concise but engaging. Use emoji where appropriate. Format as markdown with:
- A catchy header like \"What's New in v$version\"
- Key features/improvements as bullet points
- Any bug fixes mentioned
- A friendly closing line

Keep it under 200 words. Make users excited about the update!"

    # Call Google Gemini API
    local response
    response=$(curl -s -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=${GOOGLE_AI}" \
        -H "Content-Type: application/json" \
        -d '{
            "contents": [{
                "parts": [{"text": "'"$prompt"'"}]
            }],
            "generationConfig": {
                "temperature": 0.7,
                "maxOutputTokens": 512,
                "topP": 0.95,
                "topK": 40
            }
        }' 2>/dev/null)
    
    # Extract text from response
    local ai_notes
    ai_notes=$(echo "$response" | grep -o '"text": "[^"]*"' | sed 's/"text": "//' | sed 's/\\n/\n/g' | head -c 2000)
    
    if [ -n "$ai_notes" ] && [ "$ai_notes" != "" ]; then
        # Write release notes
        cat > "$release_notes_file" << EOF
# What's New in ArabiLogia $version

$ai_notes

---
*Generated by ArabiLogia Deploy AI*
EOF
        print_status "AI release notes generated!" "$GREEN"
        return 0
    else
        # Fallback if AI fails
        print_status "AI generation failed, using template..." "$YELLOW"
        cat > "$release_notes_file" << EOF
# What's New in ArabiLogia $version

## Features & Improvements
- New release with improvements and bug fixes
- Performance optimizations
- Updated Arabic learning content

## Bug Fixes
- Various stability improvements

---
*ArabiLogia v$version*
EOF
        return 1
    fi
}

# Main
main() {
    init_log
    clear
    show_logo
    
    check_environment || exit 1
    
    parse_args "$@"
    run_interactive_config
    
    prepare_output_directory
    update_version_files
    
    clean_gradle
    run_flutter_clean
    run_flutter_pub_get
    
    build_android
    build_linux
    publish_to_github
    
    generate_ai_release_notes
    
    show_summary
}

main "$@"